export const products = [
    {
        id: 1,
        name: "Termo de marca yanki",
        price: 45000,
        stock: 100,
        description: "El termo para verte fachero facherito",
        img: "",
    },
    {
        id: 2,
        name: "Mate de marca yanki",
        price: 20000,
        stock: 100,
        description: "El mate que hace juego con el termo para verte fachero facherito",
        img: "",
    },
    {
        id: 3,
        name: "Termo replica de marca yanki",
        price: 15000,
        stock: 1000,
        description: "El termo para verte fachero pero no facherito",
        img: "",
    },
    {
        id: 4,
        name: "Mate replica de marca yanki",
        price: 2000,
        stock: 1000,
        description: "El mate que hace juego con el termo para verte fachero pero no facherito",
        img: "",
    },
    {
        id: 5,
        name: "Pava",
        price: 1000,
        stock: 100,
        description: "Una simple pava de aluminio",
        img: "",
    },
    {
        id: 6,
        name: "Pava eléctrica gamer",
        price: 50000,
        stock: 1,
        description: "Como todo lo que tiene rgv es gamer nosotros no pudimos ser menos",
        img: "",
    },
    {
        id: 7,
        name: "Bombilla de alpaca",
        price: 400000,
        stock: 100,
        description: "Esta bombilla la hizo un monje en los montes del Himalaya, visito argentina en 1982",
        img: "",
    },
    {
        id: 8,
        name: "Bombilla de aluminio",
        price: 100,
        stock: 100,
        description: "Bombilla ideal para el terere, porque si tomas un mate caliente te asegura una quemadura de 3er grado",
        img: "",
    },
]